# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e62e71ac042012e08fd667141100aa9a1808ca8cd2f58076ce5cf2999d49af93353fe7e400d833b12256760e4d817eed2fb39be92eda96d8040f6a430a093add

test:
  secret_key_base: 533639b406ab08780478d054da46fd2793e0b5a86cfc36ff481ab69176ac6d574877b1ee00ece0ff0da5aed926e79813a0412549fbbcabcb67f82c344a8e1d2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
